<a href="https://colab.research.google.com/github/ChanggonSong/AI-Study/blob/main/%EC%8B%A4%EC%8A%B52_2_%EC%8B%AC%EC%9E%A5%EC%A7%88%ED%99%98_%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 회귀: 안정 혈압을 예측하기

In [340]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [341]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset.csv', index_col=0)
df

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,,,,,,,,,,,,,
63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [342]:
y = df['trestbps']
y

age
63    145
37    130
41    130
56    120
57    120
     ...
57    140
45    110
68    144
57    130
57    130
Name: trestbps, Length: 303, dtype: int64

In [343]:
X=df.drop('trestbps',axis=1)
X.head()

,sex,cp,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,,,,,,,,,,,,
63,1,3,233,1,0,150,0,2.3,0,0,1,1
37,1,2,250,0,1,187,0,3.5,0,0,2,1
41,0,1,204,0,0,172,0,1.4,2,0,2,1
56,1,1,236,0,1,178,0,0.8,2,0,2,1
57,0,0,354,0,1,163,1,0.6,2,0,2,1

In [344]:
patient_full = X.to_numpy()
patient_target = y.to_numpy()

In [345]:
# 그 다음 patient_full와 patient_target를 훈련 세트와 테스트 세트를 나눈다.
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(patient_full, patient_target)

In [359]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=10, include_bias=False)
poly.fit(train_input)
train_poly = poly.transform(train_input)
test_poly = poly.transform(test_input)
print(train_poly.shape)

(227, 293929)

In [360]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_poly)
train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)

In [ ]:
from sklearn.linear_model import Lasso
import matplotlib.pyplot as plt
train_score = []
test_score = []

alpha_list = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
for alpha in alpha_list:
  lasso = Lasso(alpha=alpha)
  lasso.fit(train_scaled, train_target)

  train_score.append(lasso.score(train_scaled, train_target))
  test_score.append(lasso.score(test_scaled, test_target))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.677e+02, tolerance: 7.122e+00
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.728e+02, tolerance: 7.122e+00
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.443e+02, tolerance: 7.122e+00
  model = cd_fast.enet_coordinate_descent(

In [ ]:
plt.plot(np.log10(alpha_list), train_score)
plt.plot(np.log10(alpha_list), test_score)
plt.xlabel('alpha')
plt.ylabel('R^2')
plt.show()

In [ ]:
lasso = Lasso(alpha=100)
lasso.fit(train_scaled, train_target)
print(lasso.score(train_scaled, train_target))
print(lasso.score(test_scaled, test_target))

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix

from sklearn.tree import DecisionTreeRegressor

clf_dt = DecisionTreeRegressor()
clf_dt.fit(train_input, train_target)

pred_dt = clf_dt.predict(test_input)

print(clf_dt.score(train_input, train_target))

In [ ]:
mse = np.sqrt(mean_squared_error(pred_dt, test_target))
print('평균제곱근오차', mse)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf_clf = RandomForestRegressor()
rf_clf.fit(train_input, train_target)

pred_rf = rf_clf.predict(test_input)

print(rf_clf.score(train_input, train_target))

In [ ]:
mse = np.sqrt(mean_squared_error(pred_rf, test_target))
print('평균제곱근오차', mse)

In [ ]:
from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(train_input, train_target)

pred_lr = clf_lr.predict(test_input)

print(clf_lr.score(train_input, train_target))

In [ ]:
mse = np.sqrt(mean_squared_error(pred_lr, test_target))
print('평균제곱근오차', mse)

In [ ]:
from sklearn.svm import SVR

clf_svm = SVR()
clf_svm.fit(train_input, train_target)

pred_svm = clf_svm.predict(test_input)

print(clf_svm.score(train_input, train_target))

In [ ]:
mse = np.sqrt(mean_squared_error(pred_svm, test_target))
print('평균제곱근오차', mse)